server:
  port: 9092

spring:
  application:
    name: API-Gateway-Service

  cloud:
    gateway:
      routes:
        - id: Movie-Service
          uri: lb://MOVIE-SERVICE/
          predicates:
            - Path=/movie/**

        - id: User-Service
          uri: lb://USER-SERVICE/
          predicates:
            - Path=/customer/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
